version: '3.8'


services:
  redis:
    container_name: chat_redis
    image: redis:latest
    environment:
      # Not used at this moment we can connect without password.
      REDIS_PASSWORD: redis_password
    volumes:
      - ./data/redis:/data
    ports:
      - 3034:6379
    healthcheck:
      test: "redis-cli --raw incr ping"
      timeout: 5s
      interval: 2s
      retries: 30
