version: '3.8'


services:
  postgresql:
    # If you have permissions issues on macOS, don't use virtioFS
    container_name: chat_postgresql
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker/postgresql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      timeout: 5s
      interval: 2s
      retries: 30

  redis:
    container_name: chat_redis
    image: redis:latest
    environment:
      # Not used at this moment we can connect without password.
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    healthcheck:
      test: "redis-cli --raw incr ping"
      timeout: 5s
      interval: 2s
      retries: 30
